"""empty message

Revision ID: 580067b49971
Revises: 36fcc6612e98
Create Date: 2021-09-26 17:52:20.663736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580067b49971'
down_revision = '36fcc6612e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=128), nullable=False))
    # ### end Alembic commands ###
