"""empty message

Revision ID: 70df7c911fe6
Revises: 9eef992d16df
Create Date: 2021-09-26 21:40:26.024559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70df7c911fe6'
down_revision = '9eef992d16df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adresses', 'user_idasdasdasdsa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adresses', sa.Column('user_idasdasdasdsa', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
