"""empty message

Revision ID: 9eef992d16df
Revises: 768f86fd13e7
Create Date: 2021-09-26 21:39:44.720211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eef992d16df'
down_revision = '768f86fd13e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adresses', 'user_idasdasdasdsa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adresses', sa.Column('user_idasdasdasdsa', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
