"""empty message

Revision ID: eec64dc07612
Revises: 70df7c911fe6
Create Date: 2021-09-26 21:40:55.118633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec64dc07612'
down_revision = '70df7c911fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adresses', 'user_idasdasdasdsa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adresses', sa.Column('user_idasdasdasdsa', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
